In [12]:
import pandas as pd

In [13]:
base_ano_meta = pd.read_excel('..\exports\dados_exportados_jira_por_ano.xlsx', sheet_name='Sheet1')
base_metas_apuracao = pd.read_excel('..\exports\dados_exportados_jira.xlsx', sheet_name='Sheet1')

<>:1: SyntaxWarning: invalid escape sequence '\e'
<>:2: SyntaxWarning: invalid escape sequence '\e'
<>:1: SyntaxWarning: invalid escape sequence '\e'
<>:2: SyntaxWarning: invalid escape sequence '\e'
C:\Users\P0165559\AppData\Local\Temp\ipykernel_17864\2986698024.py:1: SyntaxWarning: invalid escape sequence '\e'
  base_ano_meta = pd.read_excel('..\exports\dados_exportados_jira_por_ano.xlsx', sheet_name='Sheet1')
C:\Users\P0165559\AppData\Local\Temp\ipykernel_17864\2986698024.py:2: SyntaxWarning: invalid escape sequence '\e'
  base_metas_apuracao = pd.read_excel('..\exports\dados_exportados_jira.xlsx', sheet_name='Sheet1')

In [14]:
relacao_ano_meta = base_ano_meta[['Responsável', 'Ano da Meta']]

In [15]:
relacao_ano_meta[relacao_ano_meta['Responsável'] == 'ASPLAGMETA-2772']

Empty DataFrame
Columns: [Responsável, Ano da Meta]
Index: []

In [16]:
# map 'Ano da Meta' from relacao_ano_meta to base_metas_apuracao where Chave == Responsável
mapping = relacao_ano_meta.set_index('Responsável')['Ano da Meta']
base_metas_apuracao['Ano da Meta'] = base_metas_apuracao['Chave'].map(mapping).fillna(base_metas_apuracao['Ano da Meta'])

In [17]:
base_metas_apuracao[['Ano da Meta', 'META_ID', 'Responsável', 'Chave', 'Resumo']].head(14)

,Ano da Meta,META_ID,Responsável,Chave,Resumo
0,NaN,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2814,Apurado no período
1,NaN,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2813,Dezembro
2,NaN,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2812,Novembro
3,NaN,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2811,Outubro
4,NaN,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2810,Setembro
5,NaN,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2809,Agosto
6,NaN,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2808,Julho
7,NaN,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2807,Junho
8,NaN,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2806,Maio
9,NaN,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2805,Abril
10,NaN,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2804,Março
11,NaN,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2803,Fevereiro
12,2025.0,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2802,Janeiro
13,2025.0,NaN,ASPLAGMETA-2802,Resumo,TJMG 129 - Executar 100% (cem por cento) do pr...

In [18]:
# preencher valores ausentes de "Ano da Meta" em base_metas_apuracao usando o valor existente para o mesmo META_ID
na_before = base_metas_apuracao['Ano da Meta'].isna().sum()

base_metas_apuracao['Ano da Meta'] = base_metas_apuracao['Ano da Meta'].fillna(
    base_metas_apuracao.groupby('META_ID')['Ano da Meta'].transform(
        lambda x: x.dropna().iloc[0] if x.dropna().any() else float('nan')
    )
)

na_after = base_metas_apuracao['Ano da Meta'].isna().sum()
print(f"Ano da Meta: NaN antes={na_before}, depois={na_after}")

Ano da Meta: NaN antes=858, depois=4

In [19]:
base_metas_apuracao[['Ano da Meta', 'META_ID', 'Responsável', 'Chave', 'Resumo']].head(14)

,Ano da Meta,META_ID,Responsável,Chave,Resumo
0,2025.0,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2814,Apurado no período
1,2025.0,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2813,Dezembro
2,2025.0,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2812,Novembro
3,2025.0,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2811,Outubro
4,2025.0,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2810,Setembro
5,2025.0,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2809,Agosto
6,2025.0,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2808,Julho
7,2025.0,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2807,Junho
8,2025.0,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2806,Maio
9,2025.0,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2805,Abril
10,2025.0,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2804,Março
11,2025.0,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2803,Fevereiro
12,2025.0,ASPLAGMETA-2801,Sem responsável,ASPLAGMETA-2802,Janeiro
13,2025.0,NaN,ASPLAGMETA-2802,Resumo,TJMG 129 - Executar 100% (cem por cento) do pr...

In [ ]:
base_metas_apuracao.to_excel('dados_exportados_jira_adaptado.xlsx', index=False)

: