In [62]:
import pandas as pd

In [63]:
base_ano_meta = pd.read_excel('dados_exportados_jira_por_ano.xlsx', sheet_name='Sheet1')
base_metas_apuracao = pd.read_excel('dados_exportados_jira.xlsx', sheet_name='Sheet1')

In [64]:
relacao_ano_meta = base_ano_meta[['Responsável', 'Ano da Meta']]

In [65]:
relacao_ano_meta[relacao_ano_meta['Responsável'] == 'ASPLAGMETA-2772']

Empty DataFrame
Columns: [Responsável, Ano da Meta]
Index: []

In [66]:
# map 'Ano da Meta' from relacao_ano_meta to base_metas_apuracao where Chave == Responsável
mapping = relacao_ano_meta.set_index('Responsável')['Ano da Meta']
base_metas_apuracao['Ano da Meta'] = base_metas_apuracao['Chave'].map(mapping).fillna(base_metas_apuracao['Ano da Meta'])

In [67]:
base_metas_apuracao[['Ano da Meta', 'META_ID', 'Responsável', 'Chave', 'Resumo']].head(14)

,Ano da Meta,META_ID,Responsável,Chave,Resumo
0,NaN,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2771,Apurado no período
1,NaN,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2770,Dezembro
2,NaN,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2769,Novembro
3,NaN,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2768,Outubro
4,NaN,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2767,Setembro
5,NaN,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2766,Agosto
6,NaN,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2765,Julho
7,NaN,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2764,Junho
8,NaN,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2763,Maio
9,NaN,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2762,Abril
10,NaN,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2761,Março
11,NaN,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2760,Fevereiro
12,2025.0,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2759,Janeiro
13,NaN,ASPLAGMETA-2114,Não atribuído,ASPLAGMETA-2758,Apurado no período

In [68]:
# preencher valores ausentes de "Ano da Meta" em base_metas_apuracao usando o valor existente para o mesmo META_ID
na_before = base_metas_apuracao['Ano da Meta'].isna().sum()

base_metas_apuracao['Ano da Meta'] = base_metas_apuracao['Ano da Meta'].fillna(
    base_metas_apuracao.groupby('META_ID')['Ano da Meta'].transform(
        lambda x: x.dropna().iloc[0] if x.dropna().any() else float('nan')
    )
)

na_after = base_metas_apuracao['Ano da Meta'].isna().sum()
print(f"Ano da Meta: NaN antes={na_before}, depois={na_after}")

Ano da Meta: NaN antes=858, depois=4

In [69]:
base_metas_apuracao[['Ano da Meta', 'META_ID', 'Responsável', 'Chave', 'Resumo']].head(14)

,Ano da Meta,META_ID,Responsável,Chave,Resumo
0,2025.0,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2771,Apurado no período
1,2025.0,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2770,Dezembro
2,2025.0,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2769,Novembro
3,2025.0,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2768,Outubro
4,2025.0,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2767,Setembro
5,2025.0,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2766,Agosto
6,2025.0,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2765,Julho
7,2025.0,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2764,Junho
8,2025.0,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2763,Maio
9,2025.0,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2762,Abril
10,2025.0,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2761,Março
11,2025.0,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2760,Fevereiro
12,2025.0,ASPLAGMETA-2113,Não atribuído,ASPLAGMETA-2759,Janeiro
13,2025.0,ASPLAGMETA-2114,Não atribuído,ASPLAGMETA-2758,Apurado no período

In [70]:
base_metas_apuracao.to_excel('dados_exportados_jira_adaptado.xlsx', index=False)